import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = "English";

  String get currentLanguage => _currentLanguage;

  LanguageProvider() {
    _loadLanguage();
  }

  void setLanguage(String language) async {
    _currentLanguage = language;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    prefs.setString('selected_language', language);
  }

  void _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('selected_language') ?? "English";
    notifyListeners();
  }

  String translate(String key) {
    if (_translations[_currentLanguage] != null && _translations[_currentLanguage]![key] != null) {
      return _translations[_currentLanguage]![key]!;
    }
    return _translations["English"]![key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    "English": {
      "settings_title": "Account Settings",
      "edit_profile": "EDIT PROFILE",
      "full_name": "Full name",
      "email": "Email",
      "update_profile": "Update Profile",
      "change_password": "CHANGE PASSWORD",
      "new_password": "New password",
      "confirm_password": "Confirm new password",
      "update_password": "Update Password",
      "notifications": "Notifications",
      "push_notifications": "Push Notifications",
      "reward_alerts": "Reward Alerts",
      "badge_notifications": "Badge Notifications",
      "security": "Security",
      "biometric_login": "Biometric Login",
      "pin_lock": "PIN Lock",
      "active_sessions": "Active Sessions",
      "appearance": "Appearance",
      "dark_mode": "Dark Mode",
      "font_size": "Font Size",
      "language": "Language",
      "rewards": "Rewards",
      "my_points": "My Points",
      "redemption_history": "Redemption History",
      "badge_progress": "Badge Progress",
      "qr_code": "QR Code",
      "view_qr": "View QR Code",
      "qr_info": "QR Information",
      "accessibility": "Accessibility",
      "text_size": "Text Size",
      "high_contrast": "High Contrast",
      "reduce_motion": "Reduce Motion",
      "help_support": "Help & Support",
      "faq": "FAQ",
      "contact_support": "Contact Support",
      "report_problem": "Report a Problem",
      "about": "About",
      "app_version": "App Version",
      "certifications": "Certifications",
      "terms_conditions": "Terms & Conditions",
      "privacy_policy": "Privacy Policy",
      "share_app": "Share App",
      "share_app_info": "Let others scan this QR code to download the SmartBin app.",
      "delete_account": "Delete Account",
      "hi": "Hi",
      "eco_beginner": "Eco Beginner",
      "eco_recycler": "Eco Recycler",
      "eco_warrior": "Eco Warrior",
      "green_guardian": "Green Guardian",
      "recycling_champion": "Recycling Champion",
      "sustainability_hero": "Sustainability Hero",
      "pts_to_next": "pts to next level",
      "generate_qr": "Generate QR to dispose",
      "points": "Points",
      "items_recycled": "Items recycled",
      "recent_activity": "RECENT ACTIVITY",
      "view_all": "View all",
      "home": "Home",
      "rank": "Rank",
      "profile": "Profile",
    },
    "Filipino": {
      "settings_title": "Mga Setting ng Account",
      "edit_profile": "I-EDIT ANG PROFILE",
      "full_name": "Buong pangalan",
      "email": "Email",
      "update_profile": "I-update ang Profile",
      "change_password": "PALITAN ANG PASSWORD",
      "new_password": "Bagong password",
      "confirm_password": "Kumpirmahin ang bagong password",
      "update_password": "I-update ang Password",
      "notifications": "Mga Abiso",
      "push_notifications": "Mga Push Notification",
      "reward_alerts": "Mga Alerto sa Gantimpala",
      "badge_notifications": "Mga Abiso sa Badge",
      "security": "Seguridad",
      "biometric_login": "Biometric na Pag-login",
      "pin_lock": "PIN Lock",
      "active_sessions": "Mga Aktibong Session",
      "appearance": "Hitsura",
      "dark_mode": "Dark Mode",
      "font_size": "Laki ng Font",
      "language": "Wika",
      "rewards": "Mga Gantimpala",
      "my_points": "Aking mga Puntos",
      "redemption_history": "Kasaysayan ng Pag-redeem",
      "badge_progress": "Pag-unlad ng Badge",
      "qr_code": "QR Code",
      "view_qr": "Tingnan ang QR Code",
      "qr_info": "Impormasyon ng QR",
      "accessibility": "Pag-access",
      "text_size": "Laki ng Teksto",
      "high_contrast": "Mataas na Contrast",
      "reduce_motion": "Bawasan ang Paggalaw",
      "help_support": "Tulong at Suporta",
      "faq": "FAQ",
      "contact_support": "Makipag-ugnayan sa Suporta",
      "report_problem": "Mag-ulat ng Problema",
      "about": "Tungkol sa",
      "app_version": "Bersyon ng App",
      "certifications": "Mga Sertipikasyon",
      "terms_conditions": "Mga Tuntunin at Kundisyon",
      "privacy_policy": "Patakaran sa Privacy",
      "share_app": "Ibahagi ang App",
      "share_app_info": "Hayaan ang iba na i-scan ang QR code na ito para ma-download ang SmartBin app.",
      "delete_account": "I-delete ang Account",
      "hi": "Kumusta",
      "pts_to_next": "puntos para sa susunod na level",
      "generate_qr": "Bumuo ng QR para itapon",
      "points": "Mga Puntos",
      "items_recycled": "Mga recycled na gamit",
      "recent_activity": "MAKABAGONG AKTIBIDAD",
      "view_all": "Tingnan lahat",
      "home": "Home",
      "rank": "Ranggo",
      "profile": "Profile",
      "active_sessions": "Mga Session",
    },
    "Hiligaynon": {
      "settings_title": "Mga Setting sang Account",
      "edit_profile": "I-EDIT ANG PROFILE",
      "full_name": "Bilog nga ngalan",
      "email": "Email",
      "update_profile": "I-update ang Profile",
      "change_password": "ILISAN ANG PASSWORD",
      "new_password": "Bag-o nga password",
      "confirm_password": "Kumpirmaha ang bag-o nga password",
      "update_password": "I-update ang Password",
      "notifications": "Mga Pahibalo",
      "push_notifications": "Mga Push Notification",
      "reward_alerts": "Mga Alerto sa Padula",
      "badge_notifications": "Mga Pahibalo sa Badge",
      "security": "Seguridad",
      "biometric_login": "Biometric nga Pag-login",
      "pin_lock": "PIN Lock",
      "active_sessions": "Mga Aktibo nga Session",
      "appearance": "Hitsura",
      "dark_mode": "Dark Mode",
      "font_size": "Kadakuon sang Font",
      "language": "Hambal",
      "rewards": "Mga Padula",
      "my_points": "Akon mga Puntos",
      "redemption_history": "Kasaysayan sang Pag-redeem",
      "badge_progress": "Pag-uswag sang Badge",
      "qr_code": "QR Code",
      "view_qr": "Tan-awa ang QR Code",
      "qr_info": "Impormasyon sang QR",
      "accessibility": "Pag-access",
      "text_size": "Kadakuon sang Teksto",
      "high_contrast": "Mataas nga Contrast",
      "reduce_motion": "Buhinan ang Paghulag",
      "help_support": "Tabang kag Suporta",
      "faq": "FAQ",
      "contact_support": "Makig-angot sa Suporta",
      "report_problem": "Mag-report sang Problema",
      "about": "Tungod sa",
      "app_version": "Bersyon sang App",
      "certifications": "Mga Sertipikasyon",
      "terms_conditions": "Mga Kasugtanan kag Kundisyon",
      "privacy_policy": "Patakaran sa Pribasiya",
      "share_app": "I-share ang App",
      "share_app_info": "Pasugtan ang iban nga i-scan ini nga QR code para ma-download ang SmartBin app.",
      "delete_account": "I-delete ang Account",
      "hi": "Kamusta",
      "pts_to_next": "puntos para sa sunod nga level",
      "generate_qr": "Maghimo sang QR para ihaboy",
      "points": "Mga Puntos",
      "items_recycled": "Mga gamit nga na-recycle",
      "recent_activity": "BAG-O NGA AKTIBIDAD",
      "view_all": "Tan-awa tanan",
      "home": "Home",
      "rank": "Ranggo",
      "profile": "Profile",
      "active_sessions": "Mga Session",
    }
  };
}
