org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.manager=allow
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
systemProp.android.home=C\:\\Users\\ADMIN\\AppData\\Local\\Android\\Sdk
systemProp.env.ANDROID_HOME=C\:\\Users\\ADMIN\\AppData\\Local\\Android\\Sdk
org.gradle.java.home=C\:\\tools\\jdk17\\jdk-17.0.20.1+1
# systemProp.user.home=C\:\\gradle_home
kotlin.jvm.target.validation.mode=ignore